---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: camunda-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camunda-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: custom-metrics
      metricName: camunda_queue_count
      targetValue: 30